# Set the default shell to bash
set-option -g default-shell /bin/bash

# Fix the hell ^D fail on exiting
set-option -g default-command "stty eof '^D' 2>/dev/null; exec bash"

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g history-limit 65536

